name: Build with Pygbag

on:
  push:
    branches:
      - main  # or the branch you want to trigger on
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Nikki Asteinza - Convex Hull
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the version of Python you want

    - name: Install Pygbag
      run: |
        echo "Attempting to install pygbag"
        python -m pip install pygbag
        echo "Successfully installed pygbag"

    - name: Build the game
      run: |
        echo "Attempting to build the game"
        python -m pygbag --build $GITHUB_WORKSPACE/main.py --optimize
        echo "Successfully built the game and compiled to WebAssembly"
        ls build/web  # List contents of the build folder to verify

    - name: Upload to GitHub pages branch gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web
